"""Remote Set UI sections — order matches LuxPower portal PDF (SN 2453530335)."""
from __future__ import annotations

from typing import Any

# Order: Common → Application → System Grid Connect → Connection → Power Command
#        → Charge Setting → Discharge → Other → Reset → Dongle Set

SETTINGS_SECTIONS: list[dict[str, Any]] = [
    {
        "id": "common",
        "title": "Common Setting",
        "fields": [
            {
                "id": "inverter_time",
                "label": "Time",
                "type": "hold",
                "param": "HOLD_TIME",
                "widget": "text",
                "hint": "YYYY-MM-DD HH:MM:SS",
            },
            {
                "id": "pv_input_mode",
                "label": "PV Input Mode",
                "type": "hold",
                "param": "HOLD_PV_INPUT_MODE",
                "widget": "select",
                "options": [
                    {"value": "0", "label": "0: Independent"},
                    {"value": "1", "label": "1: DC Source"},
                    {"value": "2", "label": "2: MPPT parallel"},
                    {"value": "3", "label": "3: Two MPPT same"},
                    {"value": "4", "label": "4: Two MPPT different"},
                ],
            },
            {
                "id": "model_group",
                "type": "subgroup",
                "title": "Model",
                "layout": "two-col",
                "fields": [
                    {
                        "id": "battery_type",
                        "label": "Battery Type",
                        "type": "hold",
                        "param": "HOLD_MODEL_batteryType",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "0: Lead-acid"},
                            {"value": "1", "label": "1: (other)"},
                            {"value": "2", "label": "2: Lithium"},
                        ],
                    },
                    {
                        "id": "lithium_type",
                        "label": "Lithium Type",
                        "type": "hold",
                        "param": "HOLD_MODEL_lithiumType",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "0: (default)"},
                            {"value": "1", "label": "1: (other)"},
                            {"value": "2", "label": "2: Pylon/Freedom Won/Sola…"},
                        ],
                    },
                    {
                        "id": "lead_acid_capacity",
                        "label": "Lead-acid Capacity",
                        "type": "hold",
                        "param": "HOLD_MODEL_leadAcidType",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "0: 50Ah"},
                            {"value": "1", "label": "1: 100Ah"},
                            {"value": "2", "label": "2: 200Ah"},
                        ],
                    },
                    {
                        "id": "rule",
                        "label": "Rule",
                        "type": "hold",
                        "param": "HOLD_MODEL_rule",
                        "widget": "select",
                        "options": [
                            {"value": "16", "label": "16: SA (NRS097-1)"},
                        ],
                    },
                ],
            },
            {
                "id": "standby",
                "label": "Normal / Standby",
                "type": "func",
                "param": "FUNC_SET_TO_STANDBY",
                "widget": "mode",
                "modes": [
                    {"value": False, "label": "Normal"},
                    {"value": True, "label": "Standby"},
                ],
            },
            {
                "id": "battery_eco",
                "label": "Battery ECO Enable",
                "type": "func",
                "param": "FUNC_BATTERY_ECO_EN",
                "widget": "toggle",
            },
            {
                "id": "restart_inverter",
                "label": "Restart Inverter",
                "type": "action",
                "action": "restart",
                "buttonLabel": "Restart",
            },
            {
                "id": "buzzer",
                "label": "Buzzer Enable",
                "type": "func",
                "param": "FUNC_BUZZER_EN",
                "widget": "toggle",
            },
        ],
    },
    {
        "id": "application",
        "title": "Application Setting",
        "fields": [
            {
                "id": "eps_voltage",
                "label": "EPS Voltage Set (V)",
                "type": "hold",
                "param": "HOLD_EPS_VOLT_SET",
                "widget": "select",
                "options": [{"value": "230", "label": "230"}, {"value": "240", "label": "240"}],
            },
            {
                "id": "eps_frequency",
                "label": "EPS Frequency Set (Hz)",
                "type": "hold",
                "param": "HOLD_EPS_FREQ_SET",
                "widget": "select",
                "options": [{"value": "50", "label": "50"}, {"value": "60", "label": "60"}],
            },
            {
                "id": "ac_input_range",
                "label": "AC Input Range",
                "type": "hold",
                "param": "HOLD_MAX_AC_INPUT_POWER",
                "widget": "select",
                "options": [
                    {"value": "1", "label": "1: UPS (Utility 170–280 V)"},
                    {"value": "2", "label": "2: Appliance"},
                ],
            },
            {
                "id": "pv_grid_off",
                "label": "PV Grid Off",
                "type": "func",
                "param": "FUNC_PV_GRID_OFF_EN",
                "widget": "toggle",
            },
            {
                "id": "ac_first_group",
                "type": "subgroup",
                "title": "AC First",
                "fields": [
                    {
                        "id": "ac_first_1",
                        "label": "Period 1",
                        "type": "time_range",
                        "startHour": "HOLD_AC_FIRST_START_HOUR",
                        "startMinute": "HOLD_AC_FIRST_START_MINUTE",
                        "endHour": "HOLD_AC_FIRST_END_HOUR",
                        "endMinute": "HOLD_AC_FIRST_END_MINUTE",
                    },
                    {
                        "id": "ac_first_2",
                        "label": "Period 2",
                        "type": "time_range",
                        "startHour": "HOLD_AC_FIRST_START_HOUR_1",
                        "startMinute": "HOLD_AC_FIRST_START_MINUTE_1",
                        "endHour": "HOLD_AC_FIRST_END_HOUR_1",
                        "endMinute": "HOLD_AC_FIRST_END_MINUTE_1",
                    },
                    {
                        "id": "ac_first_3",
                        "label": "Period 3",
                        "type": "time_range",
                        "startHour": "HOLD_AC_FIRST_START_HOUR_2",
                        "startMinute": "HOLD_AC_FIRST_START_MINUTE_2",
                        "endHour": "HOLD_AC_FIRST_END_HOUR_2",
                        "endMinute": "HOLD_AC_FIRST_END_MINUTE_2",
                    },
                ],
            },
            {
                "id": "hybrid_group",
                "type": "subgroup",
                "title": "Hybrid Setting",
                "fields": [
                    {
                        "id": "take_load_together",
                        "label": "PV & AC Take Load Jointly",
                        "type": "func",
                        "param": "FUNC_TAKE_LOAD_TOGETHER",
                        "widget": "toggle",
                    },
                    {
                        "id": "feed_in_grid",
                        "label": "Export to Grid",
                        "type": "func",
                        "param": "FUNC_FEED_IN_GRID_EN",
                        "widget": "toggle",
                    },
                    {
                        "id": "export_percent",
                        "label": "Export Power Percent (%)",
                        "type": "hold",
                        "param": "HOLD_FEED_IN_GRID_POWER_PERCENT",
                        "widget": "number",
                        "min": 0,
                        "max": 100,
                    },
                ],
            },
            {
                "id": "parallel_group",
                "type": "subgroup",
                "title": "Parallel Settings",
                "fields": [
                    {
                        "id": "parallel_system",
                        "label": "Set System Type",
                        "type": "hold",
                        "param": "HOLD_SET_MASTER_OR_SLAVE",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "No Parallel"},
                            {"value": "1", "label": "Parallel master"},
                            {"value": "2", "label": "Parallel slave"},
                        ],
                    },
                    {
                        "id": "composed_phase",
                        "label": "Set Composed Phase",
                        "type": "hold",
                        "param": "HOLD_SET_COMPOSED_PHASE",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "Phase R"},
                            {"value": "1", "label": "Phase R"},
                            {"value": "2", "label": "Phase S"},
                            {"value": "3", "label": "Phase T"},
                        ],
                    },
                    {
                        "id": "battery_shared",
                        "label": "Battery Shared",
                        "type": "func",
                        "param": "FUNC_BAT_SHARED",
                        "widget": "toggle",
                    },
                ],
            },
            {
                "id": "grid_loss_warning",
                "label": "Grid Loss Warning Clear",
                "type": "func",
                "param": "FUNC_GRID_ON_POWER_SS_EN",
                "widget": "toggle",
                "note": "Maps to FUNC_GRID_ON_POWER_SS_EN from cloud read; confirm in portal if behaviour differs.",
            },
        ],
    },
    {
        "id": "system_grid_connect",
        "title": "System Grid Connect Setting",
        "layout": "two-col",
        "fields": [
            {
                "id": "grid_volt_lim1_high",
                "label": "Grid Volt Limit1 High (V)",
                "type": "hold",
                "param": "HOLD_GRID_VOLT_LIMIT1_HIGH",
                "widget": "number",
            },
            {
                "id": "grid_volt_lim1_low",
                "label": "Grid Volt Limit1 Low (V)",
                "type": "hold",
                "param": "HOLD_GRID_VOLT_LIMIT1_LOW",
                "widget": "number",
            },
            {
                "id": "grid_freq_lim1_high",
                "label": "Grid Freq Limit1 High (Hz)",
                "type": "hold",
                "param": "HOLD_GRID_FREQ_LIMIT1_HIGH",
                "widget": "number",
            },
            {
                "id": "grid_freq_lim1_low",
                "label": "Grid Freq Limit1 Low (Hz)",
                "type": "hold",
                "param": "HOLD_GRID_FREQ_LIMIT1_LOW",
                "widget": "number",
            },
        ],
    },
    {
        "id": "connection",
        "title": "Connection",
        "layout": "two-col",
        "fields": [
            {
                "id": "connect_time",
                "label": "Connect Time (s)",
                "type": "hold",
                "param": "HOLD_CONNECT_TIME",
                "widget": "number",
                "min": 0,
                "max": 600,
            },
            {
                "id": "reconnect_time",
                "label": "Reconnect Time (s)",
                "type": "hold",
                "param": "HOLD_RECONNECT_TIME",
                "widget": "number",
                "min": 0,
                "max": 600,
            },
            {
                "id": "grid_volt_conn_high",
                "label": "Grid Volt Connect High (V)",
                "type": "hold",
                "param": "HOLD_GRID_VOLT_CONN_HIGH",
                "widget": "number",
            },
            {
                "id": "grid_volt_conn_low",
                "label": "Grid Volt Connect Low (V)",
                "type": "hold",
                "param": "HOLD_GRID_VOLT_CONN_LOW",
                "widget": "number",
            },
            {
                "id": "grid_freq_conn_high",
                "label": "Grid Freq Connect High (Hz)",
                "type": "hold",
                "param": "HOLD_GRID_FREQ_CONN_HIGH",
                "widget": "number",
            },
            {
                "id": "grid_freq_conn_low",
                "label": "Grid Freq Connect Low (Hz)",
                "type": "hold",
                "param": "HOLD_GRID_FREQ_CONN_LOW",
                "widget": "number",
            },
        ],
    },
    {
        "id": "power_command",
        "title": "Power Command",
        "fields": [
            {
                "id": "active_power_percent",
                "label": "Active Power Percent (%)",
                "type": "hold",
                "param": "HOLD_ACTIVE_POWER_PERCENT_CMD",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
        ],
    },
    {
        "id": "charge",
        "title": "Charge Setting",
        "fields": [
            {
                "id": "charge_current_limit",
                "label": "Charge Current Limit (Adc)",
                "type": "hold",
                "param": "HOLD_LEAD_ACID_CHARGE_RATE",
                "widget": "number",
                "min": 0,
                "max": 110,
                "placeholder": "[0, 110]",
            },
            {
                "id": "lead_acid_group",
                "type": "subgroup",
                "title": "Lead Acid",
                "layout": "two-col",
                "fields": [
                    {
                        "id": "la_charge_volt",
                        "label": "Charge Voltage (V)",
                        "type": "hold",
                        "param": "HOLD_LEAD_ACID_CHARGE_VOLT_REF",
                        "widget": "number",
                        "min": 50,
                        "max": 58,
                    },
                    {
                        "id": "la_eq_volt",
                        "label": "Equalization Voltage (V)",
                        "type": "hold",
                        "param": "HOLD_EQUALIZATION_VOLTAGE",
                        "widget": "number",
                        "min": 50,
                        "max": 59,
                    },
                    {
                        "id": "la_float_volt",
                        "label": "Floating Voltage (V)",
                        "type": "hold",
                        "param": "HOLD_FLOATING_VOLTAGE",
                        "widget": "number",
                        "min": 50,
                        "max": 58,
                    },
                    {
                        "id": "la_eq_time",
                        "label": "Equalization Time (Hours)",
                        "type": "hold",
                        "param": "HOLD_EQUALIZATION_TIME",
                        "widget": "number",
                        "min": 0,
                        "max": 24,
                    },
                    {
                        "id": "la_eq_period",
                        "label": "Equalization Period (Days)",
                        "type": "hold",
                        "param": "HOLD_EQUALIZATION_PERIOD",
                        "widget": "number",
                        "min": 0,
                        "max": 365,
                    },
                ],
            },
            {
                "id": "ac_charge_group",
                "type": "subgroup",
                "title": "AC Charge",
                "layout": "wide",
                "fields": [
                    {
                        "id": "ac_charge_based_on",
                        "label": "AC Charge Based On",
                        "type": "bit",
                        "param": "BIT_AC_CHARGE_TYPE",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "Voltage"},
                            {"value": "1", "label": "Time"},
                            {"value": "2", "label": "Mixed"},
                            {"value": "3", "label": "Battery SOC"},
                        ],
                    },
                    {
                        "id": "ac_charge_battery_current",
                        "label": "AC Charge Battery Current (A)",
                        "type": "hold",
                        "param": "HOLD_AC_CHARGE_BATTERY_CURRENT",
                        "widget": "number",
                        "min": 0,
                        "max": 250,
                    },
                    {
                        "id": "ac_chg_start_1",
                        "label": "AC Charge Start Time 1",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_START_HOUR",
                        "minuteParam": "HOLD_AC_CHARGE_START_MINUTE",
                    },
                    {
                        "id": "ac_chg_end_1",
                        "label": "AC Charge End Time 1",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_END_HOUR",
                        "minuteParam": "HOLD_AC_CHARGE_END_MINUTE",
                    },
                    {
                        "id": "ac_chg_start_2",
                        "label": "AC Charge Start Time 2",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_START_HOUR_1",
                        "minuteParam": "HOLD_AC_CHARGE_START_MINUTE_1",
                    },
                    {
                        "id": "ac_chg_end_2",
                        "label": "AC Charge End Time 2",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_END_HOUR_1",
                        "minuteParam": "HOLD_AC_CHARGE_END_MINUTE_1",
                    },
                    {
                        "id": "ac_chg_start_3",
                        "label": "AC Charge Start Time 3",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_START_HOUR_2",
                        "minuteParam": "HOLD_AC_CHARGE_START_MINUTE_2",
                    },
                    {
                        "id": "ac_chg_end_3",
                        "label": "AC Charge End Time 3",
                        "type": "time_pair",
                        "hourParam": "HOLD_AC_CHARGE_END_HOUR_2",
                        "minuteParam": "HOLD_AC_CHARGE_END_MINUTE_2",
                    },
                    {
                        "id": "ac_chg_start_volt",
                        "label": "AC Charge Start Battery Voltage (V)",
                        "type": "hold",
                        "param": "HOLD_AC_CHARGE_START_BATTERY_VOLTAGE",
                        "widget": "number",
                        "disableWhen": {"param": "BIT_AC_CHARGE_TYPE", "socValues": ["3"]},
                    },
                    {
                        "id": "ac_chg_end_volt",
                        "label": "AC Charge End Battery Voltage (V)",
                        "type": "hold",
                        "param": "HOLD_AC_CHARGE_END_BATTERY_VOLTAGE",
                        "widget": "number",
                        "disableWhen": {"param": "BIT_AC_CHARGE_TYPE", "socValues": ["3"]},
                    },
                    {
                        "id": "ac_chg_start_soc",
                        "label": "AC Charge Start Battery SOC (%)",
                        "type": "hold",
                        "param": "HOLD_AC_CHARGE_START_BATTERY_SOC",
                        "widget": "number",
                        "min": 0,
                        "max": 100,
                    },
                    {
                        "id": "ac_chg_end_soc",
                        "label": "AC Charge End Battery SOC (%)",
                        "type": "hold",
                        "param": "HOLD_AC_CHARGE_END_BATTERY_SOC",
                        "widget": "number",
                        "min": 0,
                        "max": 100,
                    },
                ],
            },
            {
                "id": "generator_charge_group",
                "type": "subgroup",
                "title": "Generator Charge",
                "layout": "two-col",
                "fields": [
                    {
                        "id": "gen_charge_type",
                        "label": "Generator Charge Type",
                        "type": "bit",
                        "param": "BIT_GENERATOR_CHARGE_TYPE",
                        "widget": "select",
                        "options": [
                            {"value": "0", "label": "Voltage"},
                            {"value": "1", "label": "Battery SOC"},
                            {"value": "2", "label": "Time"},
                        ],
                    },
                    {
                        "id": "gen_charge_current",
                        "label": "Generator Charge Battery Current (A)",
                        "type": "hold",
                        "param": "OFF_GRID_HOLD_MAX_GEN_CHG_BAT_CURR",
                        "widget": "number",
                        "min": 0,
                        "max": 250,
                    },
                    {
                        "id": "gen_start_volt",
                        "label": "Generator Charge Start Battery Voltage (V)",
                        "type": "hold",
                        "param": "OFF_GRID_HOLD_GEN_CHG_START_VOLT",
                        "widget": "number",
                        "disableWhen": {"param": "BIT_GENERATOR_CHARGE_TYPE", "socValues": ["1"]},
                    },
                    {
                        "id": "gen_end_volt",
                        "label": "Generator Charge End Battery Voltage (V)",
                        "type": "hold",
                        "param": "OFF_GRID_HOLD_GEN_CHG_END_VOLT",
                        "widget": "number",
                        "disableWhen": {"param": "BIT_GENERATOR_CHARGE_TYPE", "socValues": ["1"]},
                    },
                    {
                        "id": "gen_start_soc",
                        "label": "Generator Charge Start Battery SOC (%)",
                        "type": "hold",
                        "param": "OFF_GRID_HOLD_GEN_CHG_START_SOC",
                        "widget": "number",
                        "min": 0,
                        "max": 100,
                    },
                    {
                        "id": "gen_end_soc",
                        "label": "Generator Charge End Battery SOC (%)",
                        "type": "hold",
                        "param": "OFF_GRID_HOLD_GEN_CHG_END_SOC",
                        "widget": "number",
                        "min": 0,
                        "max": 100,
                    },
                    {
                        "id": "gen_max_power",
                        "label": "Max. Generator Input Power (W)",
                        "type": "hold",
                        "param": "HOLD_MAX_GENERATOR_INPUT_POWER",
                        "widget": "number",
                        "min": 0,
                        "max": 20000,
                    },
                    {
                        "id": "gen_boost",
                        "label": "Generator Boost",
                        "type": "func",
                        "param": "FUNC_GEN_CTRL",
                        "widget": "toggle",
                    },
                ],
            },
        ],
    },
    {
        "id": "discharge",
        "title": "Discharge Setting",
        "layout": "two-col",
        "fields": [
            {
                "id": "dischg_control",
                "label": "Discharge Control",
                "type": "bit",
                "param": "BIT_DISCHG_CONTROL_TYPE",
                "widget": "select",
                "options": [
                    {"value": "0", "label": "Voltage"},
                    {"value": "1", "label": "SOC (According to)"},
                ],
            },
            {
                "id": "dischg_current_limit",
                "label": "Discharge Current Limit (Adc)",
                "type": "hold",
                "param": "HOLD_LEAD_ACID_DISCHARGE_RATE",
                "widget": "number",
                "min": 0,
                "max": 110,
            },
            {
                "id": "bat_warning_volt",
                "label": "Battery Warning Voltage (V)",
                "type": "hold",
                "param": "HOLD_BATTERY_WARNING_VOLTAGE",
                "widget": "number",
                "disableWhen": {"param": "BIT_DISCHG_CONTROL_TYPE", "socValues": ["1"]},
            },
            {
                "id": "bat_warning_soc",
                "label": "Battery Warning SOC (%)",
                "type": "hold",
                "param": "HOLD_BATTERY_WARNING_SOC",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
            {
                "id": "dischg_cutoff_volt",
                "label": "Discharge Cut-off Voltage (V)",
                "type": "hold",
                "param": "HOLD_LEAD_ACID_DISCHARGE_CUT_OFF_VOLT",
                "widget": "number",
                "disableWhen": {"param": "BIT_DISCHG_CONTROL_TYPE", "socValues": ["1"]},
            },
            {
                "id": "dischg_cutoff_soc",
                "label": "Discharge Cut-off SOC (%)",
                "type": "hold",
                "param": "HOLD_SOC_LOW_LIMIT_EPS_DISCHG",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
            {
                "id": "ongrid_eod_volt",
                "label": "On Grid EOD Voltage (V)",
                "type": "hold",
                "param": "HOLD_ON_GRID_EOD_VOLTAGE",
                "widget": "number",
                "disableWhen": {"param": "BIT_DISCHG_CONTROL_TYPE", "socValues": ["1"]},
            },
            {
                "id": "ongrid_eod_soc",
                "label": "On Grid EOD SOC (%)",
                "type": "hold",
                "param": "HOLD_DISCHG_CUT_OFF_SOC_EOD",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
        ],
    },
    {
        "id": "other",
        "title": "Other Setting",
        "layout": "two-col",
        "fields": [
            {
                "id": "ct_offset",
                "label": "CT Power Offset (W)",
                "type": "hold",
                "param": "HOLD_CT_POWER_OFFSET",
                "widget": "number",
                "min": -500,
                "max": 500,
            },
            {
                "id": "fan1_speed",
                "label": "Fan 1 Max Speed (%)",
                "type": "bit",
                "param": "BIT_FAN_1_MAX_SPEED",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
            {
                "id": "fan1_slope",
                "label": "Fan 1 speed slope",
                "type": "func",
                "param": "FUNC_FAN_SPEED_SLOPE_CTRL_1",
                "widget": "toggle",
                "labels": ["Default", "New Slope"],
                "invert": True,
            },
            {
                "id": "fan2_speed",
                "label": "Fan 2 Max Speed (%)",
                "type": "bit",
                "param": "BIT_FAN_2_MAX_SPEED",
                "widget": "number",
                "min": 0,
                "max": 100,
            },
            {
                "id": "fan2_slope",
                "label": "Fan 2 speed slope",
                "type": "func",
                "param": "FUNC_FAN_SPEED_SLOPE_CTRL_2",
                "widget": "toggle",
                "labels": ["Default", "New Slope"],
                "invert": True,
            },
        ],
    },
    {
        "id": "reset",
        "title": "Reset",
        "fields": [
            {
                "id": "reset_all",
                "label": "All to Default",
                "type": "action",
                "action": "reset_defaults",
                "buttonLabel": "Reset",
                "danger": True,
            },
        ],
    },
    {
        "id": "dongle",
        "title": "Dongle Set — {dongleSn} — Wi-Fi",
        "fields": [
            {
                "id": "dongle_server",
                "label": "Server IP and Port",
                "type": "note",
                "text": "Region: Middle East & Africa (af.luxpowertek.com). Dongle server binding uses the official portal Read/Set on the dongle page — not yet wired in this clone.",
            },
        ],
    },
]
